version: 2

updates:
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: weekly
      day: thursday
    groups:
      composer:
        update-types: [minor, patch]
    labels: []
    versioning-strategy: increase

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: thursday
    groups:
      npm:
        update-types: [minor, patch]
    labels: []
    versioning-strategy: increase

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: thursday
    labels: []
