name: Style

on:
  push:
    branches-ignore: [master]

jobs:
  js:
    name: JS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get Yarn cache directory path
        id: yarn-cache-dir
        run: echo "::set-output name=path::$(yarn cache dir)"

      - name: Cache Yarn dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir.outputs.path }}
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: yarn-

      - name: Install Yarn dependencies
        run: yarn install

      - name: Run ESLint
        run: yarn format
